config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("fantasy_gambling_league.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("fantasy_gambling_league.structure.urls", namespace="structure")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fantasy_gambling_league/structure/urls.py
from django.urls import path

from . import views

app_name = 'structure'
urlpatterns = [
    path('season/create/', views.SeasonCreateView.as_view(), name='create-season'),
    path(
        'season/update/<slug:slug>/',
        views.SeasonUpdateView.as_view(),
        name='update-season'
    ),
    path(
        'season/delete/<slug:slug>/',
        views.SeasonDeleteView.as_view(),
        name='delete-season'
    ),
    path('seasons/', views.SeasonListView.as_view(), name='list-seasons'),
    path('season/detail/<slug:slug>/',
        views.SeasonDetailView.as_view(),
        name='detail-season',
    ),
    path(
        'season/<slug:season_slug>/add_gameweek/',
        views.GameweekCreateView.as_view(),
        name='create-gameweek',
    ),
    path(
        'season/<slug:season_slug>/update/<int:number>/',
        views.GameweekUpdateView.as_view(),
        name='update-gameweek',
    ),
    path(
        'season/<slug:season_slug>/delete/<int:number>/',
        views.GameweekDeleteView.as_view(),
        name='delete-gameweek',
    ),
    path(
        'season/<slug:season_slug>/detail/<int:number>/',
        views.GameweekDetailView.as_view(),
        name='detail-gameweek',
    ),
]

fantasy_gambling_league/users/urls.py
from django.urls import path

from fantasy_gambling_league.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

fantasy_gambling_league/structure/models.py
from django.db import models

from fantasy_gambling_league.users.models import User


class Season(models.Model):
    commissioner = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
    )
    players = models.ManyToManyField(User, related_name='seasons')
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    weekly_allowance = models.DecimalField(
        default=100.0,
        decimal_places=2,
        max_digits=99
    )

class Gameweek(models.Model):
    season = models.ForeignKey(
        Season,
        on_delete=models.CASCADE,
    )
    number = models.IntegerField()
    deadline = models.DateTimeField()
    spiel = models.TextField(null=True, blank=True)

fantasy_gambling_league/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

fantasy_gambling_league/structure/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.text import slugify

from .models import Season


class SeasonForm(ModelForm):
    class Meta:
        model = Season
        fields = ['name', 'weekly_allowance']

    def clean_name(self):
        slug = slugify(self.cleaned_data['name'])

        if Season.objects.filter(slug=slug).exists():
            raise ValidationError(
                'Name must not clash with existing seasons'
            )
        return self.cleaned_data['name']

fantasy_gambling_league/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

fantasy_gambling_league/structure/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, reverse
from django.utils.text import slugify
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    DeleteView,
    UpdateView,
)
from django.views.generic.list import ListView

from .forms import SeasonForm
from .models import Season, Gameweek


class CommissionerRequiredMixin:
    def get_commissioner(self):
        raise NotImplementedError()

    def dispatch(self, request, *args, **kwargs):
        commissioner = self.get_commissioner()

        if request.user == commissioner:
            return super().dispatch(request, *args, **kwargs)

        return self.handle_no_permission()


class SeasonCommissionerRequiredMixin(CommissionerRequiredMixin):
    def get_commissioner(self):
        return self.get_object().commissioner


class SeasonCreateView(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login'
    success_url = '/'
    model = Season
    form_class = SeasonForm

    def form_valid(self, form):
        form.instance.commissioner = self.request.user
        form.instance.slug = slugify(
            form.cleaned_data['name']
        )
        return super(SeasonCreateView, self).form_valid(form)


class SeasonUpdateView(LoginRequiredMixin, SeasonCommissionerRequiredMixin, UpdateView):
    login_url = '/accounts/login'
    success_url = '/'
    model = Season
    form_class = SeasonForm

    def form_valid(self, form):
        form.instance.slug = slugify(
            form.cleaned_data['name']
        )
        return super(SeasonUpdateView, self).form_valid(form)


class SeasonDeleteView(LoginRequiredMixin, SeasonCommissionerRequiredMixin, DeleteView):
    login_url = '/accounts/login'
    success_url = '/'
    model = Season

class SeasonListView(ListView):
    model = Season


class SeasonDetailView(DetailView):
    model = Season


class GameweekCommissionerRequiredMixin(CommissionerRequiredMixin):
    def get_commissioner(self):
        season_slug = self.kwargs['season_slug']
        season = get_object_or_404(Season, slug=season_slug)

        return season.commissioner


class GameweekCreateView(LoginRequiredMixin, GameweekCommissionerRequiredMixin, CreateView):
    login_url = '/accounts/login'
    success_url = '/'
    model = Gameweek
    fields = ['deadline', 'spiel', ]

    def get_context_data(self, **kwargs):
        season_slug = self.kwargs['season_slug']

        context_data = super(GameweekCreateView, self).get_context_data(**kwargs)
        context_data.update({'season_slug': season_slug})

        return context_data

    def form_valid(self, form):
        season_slug = self.kwargs['season_slug']
        season = get_object_or_404(Season, slug=season_slug)

        form.instance.season = season
        form.instance.number = season.gameweek_set.count() + 1
        return super(GameweekCreateView, self).form_valid(form)


class GameweekUpdateView(LoginRequiredMixin, GameweekCommissionerRequiredMixin, UpdateView):
    login_url = '/accounts/login'
    success_url = '/'
    model = Gameweek
    fields = ['deadline', 'spiel', ]

    def get_object(self, queryset=None):
        season_slug = self.kwargs['season_slug']
        season = get_object_or_404(Season, slug=season_slug)

        if not queryset:
            queryset = self.get_queryset()
        
        return queryset.get(
            season=season,
            number=self.kwargs['number'],
        )

    def dispatch(self, request, *args, **kwargs):
        gameweek = self.get_object()
        if gameweek.number == gameweek.season.gameweek_set.count():
            return super().dispatch(request, *args, **kwargs)

        messages.error(request, 'Cannot edit Gameweek that is not latest')

        return HttpResponseRedirect(
            redirect_to=reverse(
                'structure:detail-season',
                kwargs={'slug': gameweek.season.slug}
            ),
        )


class GameweekDeleteView(LoginRequiredMixin, GameweekCommissionerRequiredMixin, DeleteView):
    login_url = '/accounts/login'
    success_url = '/'
    model = Gameweek

    def get_object(self, queryset=None):
        season_slug = self.kwargs['season_slug']
        season = get_object_or_404(Season, slug=season_slug)

        if not queryset:
            queryset = self.get_queryset()
        
        return queryset.get(
            season=season,
            number=self.kwargs['number'],
        )

    def dispatch(self, request, *args, **kwargs):
        gameweek = self.get_object()
        if gameweek.number == gameweek.season.gameweek_set.count():
            return super().dispatch(request, *args, **kwargs)

        messages.error(request, 'Cannot edit Gameweek that is not latest')

        return HttpResponseRedirect(
            redirect_to=reverse(
                'structure:detail-season',
                kwargs={'slug': gameweek.season.slug}
            ),
        )

class GameweekDetailView(DetailView):
    model = Gameweek

    def get_object(self, queryset=None):
        season_slug = self.kwargs['season_slug']
        season = get_object_or_404(Season, slug=season_slug)

        if not queryset:
            queryset = self.get_queryset()
        
        return queryset.get(
            season=season,
            number=self.kwargs['number'],
        )

fantasy_gambling_league/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

fantasy_gambling_league/templates/structure/gameweek_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Delete Gamweek {{ object.number }}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <form method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Confirm delete?" />
    </form>
</div>
{% endblock %}

fantasy_gambling_league/templates/structure/gameweek_detail.html
{% extends "base.html" %}

{% block title %}Gameweek {{ object.number }}{% endblock %}

{% block content %}
<ul>
    <li>Deadline: {{ object.deadline }}</li>
    <li>Spiel: {{ object.spiel }}</li>
    {% if request.user == object.season.commissioner %}
    <li><a href="{% url 'structure:update-gameweek' season_slug=object.season.slug number=object.number %}">
      Update
    </a></li>
    {% endif %}
</ul>
{% endblock %}

fantasy_gambling_league/templates/structure/gameweek_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% if object %}
Update Gameweek {{ object.number }}
{% else %}
New Gameweek
{% endif %}
{% endblock %}
  

{% block content %}
  {% if object %}
  <form 
    class="form-horizontal"
    method="post"
    action="{% url 'structure:update-gameweek' season_slug=object.season.slug number=object.number %}">
  {% else %}
  <form 
    class="form-horizontal" 
    method="post" 
    action="{% url 'structure:create-gameweek' season_slug=season_slug %}">
  {% endif %}
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        {% if object %}
        <button type="submit" class="btn">Update</button>
        {% else %}
        <button type="submit" class="btn">Create</button>
        {% endif %}
      </div>
    </div>
  </form>
  {% if object %}
  <div>
    <p><a href="{% url 'structure:delete-gameweek' season_slug=object.season.slug number=object.number %}">
      Delete
    </a></p>
  </div>
  {% endif %}
{% endblock %}

fantasy_gambling_league/templates/structure/season_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Delete Season {{ object.name }}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <form method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Confirm delete?" />
    </form>
</div>
{% endblock %}

fantasy_gambling_league/templates/structure/season_detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<ul>
    <li>Weekly allowance: {{ object.weekly_allowance }}</li>
    <li>Commissioner: {{ object.commissioner }}</li>
    <li>
      <ul>
        {% for gameweek in object.gameweek_set.all %}
        <li><a href="{% url 'structure:detail-gameweek' season_slug=object.slug number=gameweek.number %}">
          Gameweek {{ gameweek.number }}
        </a></li>
        {% endfor %}
	<li><a href="{% url 'structure:create-gameweek' season_slug=object.slug %}">Create Gameweek</a></li>
      </ul>
    </li>
    {% if request.user == object.commissioner %}
    <li><a href="{% url 'structure:update-season' object.slug %}">Update</a></li>
    {% endif %}
</ul>
{% endblock %}

fantasy_gambling_league/templates/structure/season_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% if object %}
{{ object.name }}
{% else %}
New Season
{% endif %}
{% endblock %}
  

{% block content %}
  {% if object %}
  <form class="form-horizontal" method="post" action="{% url 'structure:update-season' object.slug %}">
  {% else %}
  <form class="form-horizontal" method="post" action="{% url 'structure:create-season' %}">
  {% endif %}
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        {% if object %}
        <button type="submit" class="btn">Update</button>
        {% else %}
        <button type="submit" class="btn">Create</button>
        {% endif %}
      </div>
    </div>
  </form>
  {% if object %}
  <div>
    <p><a href="{% url 'structure:delete-season' object.slug %}">Delete</a></p>
  </div>
  {% endif %}
{% endblock %}

fantasy_gambling_league/templates/structure/season_list.html
{% extends "base.html" %}

{% block title %}All Seasons{% endblock %}

{% block content %}
<ul>
    {% for season in object_list %}
    <li><a href="{% url 'structure:detail-season' season.slug %}">{{ season.name }}</a></li>
    {% endfor %}
    <li><a href="{% url 'structure:create-season' %}">Create new season</a></li>
</ul>
{% endblock %}